# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
metron:
  version: 0.7.2

logging:
  level:
    root: ERROR

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

grok:
  path:
    temp: /apps/metron/patterns/tmp

zookeeper:
  client:
    timeout:
      session: 10000
      connection: 10000

kafka:
  security:
    protocol: SASL_PLAINTEXT
  topics:
    escalation: escalation

curator:
  sleep:
    time: 1000
  max:
    retries: 3

search:
  max:
    results: 1000
    groups: 1000
  facet:
    fields: ip_src_addr,ip_dst_addr,enrichments:geo:ip_dst_addr:country

index:
  dao:
  # By default, we use the ElasticsearchDao and HBaseDao for backing updates.
     impl: org.apache.metron.elasticsearch.dao.ElasticsearchDao,org.apache.metron.indexing.dao.HBaseDao
  writer:
  # Used to retrieve the index names from the sensor index configurations.  Should be either 'elasticsearch' or 'solr'.
    name: elasticsearch

meta:
  dao:
  # By default, we use the ElasticsearchMetaAlertDao
    impl: org.apache.metron.elasticsearch.dao.ElasticsearchMetaAlertDao

spring.jpa.generate-ddl: true

user:
  settings:
    table: user_settings
    cf: cf
  job.limit: 1

pcap:
  base.path: /apps/metron/pcap/input
  base.interim.result.path: /apps/metron/pcap/interim
  final.output.path: /apps/metron/pcap/output
  page.size: 10