#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- set_fact:
    kafka_consumer_cmd: "{{ kafka_broker_home}}/bin/kafka-console-consumer.sh --zookeeper {{ zookeeper_url }} --topic {{ fastcapa_topic }} --max-messages 10 --from-beginning"

- name: Attempting to receive message(s) sent by fastcapa
  shell: "{{ kafka_consumer_cmd }}"
  async: 30
  register: kafka_consumer

- name: Waiting to receive message(s) sent by fastcapa
  async_status: jid={{ kafka_consumer.ansible_job_id }}
  register: job
  until: job.finished
  retries: 30

- fail:
    msg: "No messages received from fastcapa within timeout: {{ kafka_consumer_cmd }}"
  when: job.finished != 1

- debug: var=job

- debug: msg="Successfully received a Kafka message from fastcapa!"
